version: "3.8" #docker version
services:
  api:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project dir with container dir
    ports:
      - 80:80
      - 443:443 # for future ssl traffic